//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CGVMovieWeb.Models
{


    public class LoginViewModel
    {
        [Required(ErrorMessage = "Vui lòng nhập tên đăng nhập.")]
        [Display(Name = "Tên Đăng Nhập")]
        public string Username { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập mật khẩu.")]
        [DataType(DataType.Password)]
        [Display(Name = "Mật Khẩu")]
        public string Password { get; set; }

        [Display(Name = "Nhớ tài khoản")]
        public bool RememberMe { get; set; }
    }

    public class RegisterViewModel
    {
        [Required(ErrorMessage = "Vui lòng nhập tên đăng nhập.")]
        [Display(Name = "Tên Đăng Nhập")]
        public string Username { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập họ tên.")]
        [Display(Name = "Họ Tên")]
        public string FullName { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập mật khẩu.")]
        [DataType(DataType.Password)]
        [Display(Name = "Mật Khẩu")]
        public string Password { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập lại mật khẩu.")]
        [DataType(DataType.Password)]
        [Display(Name = "Xác Nhận Mật Khẩu")]
        [Compare("Password", ErrorMessage = "Mật khẩu không khớp.")]
        public string ConfirmPassword { get; set; }
    }

    public class TicketViewModel
    {
        public int TicketID { get; set; }
        public string Username { get; set; }
        public string MovieTitle { get; set; }
        public DateTime ShowDate { get; set; }
        public TimeSpan StartTime { get; set; }
        public string Room { get; set; }
        public decimal Price { get; set; }
        public DateTime PurchaseDate { get; set; }
        public string SeatNumber { get; set; }
        public bool PaymentConfirmation { get; set; }
        
        public string PaymentMethod { get; set; }
    }


    public class RevenueStatisticsViewModel
    {
        public string Date { get; set; }
        public decimal TotalRevenue { get; set; }
        public List<TicketViewModel> Tickets { get; set; }
    }


    public class SelectSeatViewModel
    {
        public int ShowtimeID { get; set; }
        public string MovieTitle { get; set; }
        public decimal TicketPrice { get; set; }
        public List<Seat> AvailableSeats { get; set; }
    }

    public class DatVeViewModel
    {
        public Movy Movie { get; set; } // Thông tin phim
        public List<Showtime> Showtimes { get; set; } // Danh sách các suất chiếu của phim
    }

    public class ShowtimeViewModel
    {
        public int ShowtimeID { get; set; }
        public int MovieID { get; set; }
        public DateTime ShowDate { get; set; }
        public TimeSpan StartTime { get; set; }
        public string Room { get; set; }
        public string MovieTitle { get; set; } // Thêm thuộc tính này để hiển thị tiêu đề phim
    }


    public class ReceiptViewModel
    {
        public string MovieTitle { get; set; }
        public decimal TicketPrice { get; set; }
        public List<string> SelectedSeats { get; set; }
        public DateTime PurchaseDate { get; set; }

        public bool PaymentConfirmation { get; set; }
        public string PaymentMethod { get; set; }
    }
    public class MovieViewModel
    {
        public int MovieID { get; set; }
        public string Title { get; set; }
        public string Genre { get; set; }
        public int? Duration { get; set; }
        public string Description { get; set; }
        public DateTime? ReleaseDate { get; set; }
        public double? Rating { get; set; }
        public string ImageLink { get; set; }
        public decimal TicketPrice { get; set; }
        public string LinkTrailer { get; set; }
    }
    public class CreateTicketViewModel
    {
        public List<Movy> Movies { get; set; }    // Chứa danh sách phim
        public int MovieID { get; set; }           // ID của phim được chọn
        public int ShowtimeID { get; set; }        // ID của suất chiếu được chọn
        public int SeatID { get; set; }            // ID của ghế được chọn
    }




}

